language: c
compiler:
  - clang
  - gcc
script:
  - make test
# A nudge to avoid checking in broken builds.
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - reagen@fas.harvard.edu
      - rdadolf@seas.harvard.edu
