inline:
  - '-on'
  - '-off'
balance:
  - '-on'
  - '-off'
style:
  - stp
  - flp
  - frp
factor:
  - 0
  - 2
state:
  - '-on'
  - '-off'
arrtype:
  - block
  - cyclic
opimpl:
  int:
    - dsp
    - fabric
  float:
    - fabric
    - fulldsp
    - primitivedsp
  double:
    - fabric
    - fulldsp
  half:
    - fabric
    - fulldsp
sttype:
  - ram_1p
  - ram_1wnr
  - ram_2p
  - ram_s2p
stimpl:
  - bram
stltc:
  - -1
opltc:
  - -1
POW:
  - 0.301
CLK:
  - 9.064
LATENCY:
  - 1000
LUT:
  - 2191
FF:
  - 2686
DSP:
  - 50
BRAM:
  - 0
URAM:
  - 0
SRL:
  - 0